### ISSUE TITLE
[QUESTION] When I do Shift + S in the player it skips backward, what's the hotkey to skip forward?

### ISSUE THREAD

**Issue by saieeshb** [Sraq-Zit/slickiss#3]

**Comment by saieeshb** [comment]
Ok I figured it out as ctrl+s, but It's not added in the info section of the player. Please update Slickiss player help info with Ctrl+S is forward skip along side Shift+S. It seems you forgot to do so! I'll keep the issue open so you see this.

**Comment by Sraq-Zit** [comment]
The hotkey for skipping forward is simply S not ctrl + S.
Normally, this was supposed to mean SHIFT + S or S, but now that you mention it it is vague. I will explicitly add both.
![image](https://user-images.githubusercontent.com/34834428/87494034-fb564700-c645-11ea-8617-12dc6edfe86f.png)

**Comment by saieeshb** [comment]
> The hotkey for skipping forward is simply S not ctrl + S.
> Normally, this was supposed to mean SHIFT + S or S, but now that you mention it it is vague. I will explicitly add both.
> ![image](https://user-images.githubusercontent.com/34834428/87494034-fb564700-c645-11ea-8617-12dc6edfe86f.png)

Thank you for clarifying! Enjoying the picture in picture update as well!
