### ISSUE TITLE
cloudscrape

### ISSUE THREAD

**Issue by Qukallon-1** [Sraq-Zit/slickiss#4]
sorry im cant open issue on cloudscrape repository
ERROR:root:'https://welovecloudflare.de' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "index.py", line 4, in <module>
    cookie_value, user_agent = cfscrape.get_cookie_string("https://welovecloudflare.de")
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 419, in get_cookie_string
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 386, in get_tokens
  File "/usr/local/lib/python2.7/dist-packages/requests-2.24.0-py2.7.egg/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 129, in request
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 204, in solve_cf_challenge
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 295, in solve_challenge
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

**Comment by Sraq-Zit** [comment]
Unfortunately, this website has a challenge completely different from what cfscrape repository is solving

**Comment by Qukallon-1** [comment]
but its UAM ._.

**Comment by Sraq-Zit** [comment]
> but its UAM ._.

Okay let me clarify, this module gets javascript code from the website and runs it using nodejs then passes the result to receive the cloudflare clearance cookie.
Cfscrape however handles the type of challenges that look like this 
https://github.com/Sraq-Zit/cloudflare-scrape/blob/954670774887e028cf53f197b95db0d7076c6518/cfscrape/__init__.py#L252-L254
and with websites having this challenge you found the js code such as:
![image](https://user-images.githubusercontent.com/34834428/87877347-b891c780-c9d5-11ea-8f68-8c9c0054b369.png)

in the other side, the website you provided has no such challenge, instead they inject this obfuscated which contains  the challenge to solve
![image](https://user-images.githubusercontent.com/34834428/87878635-753b5700-c9dd-11ea-8dcc-54a9b75f4390.png)

and that, apparently, is not supported by cfscrape yet

**Comment by Sraq-Zit** [comment]
> but its UAM ._.

Okay let me clarify, this module gets javascript code from the website and runs it using nodejs then passes the result to receive the cloudflare clearance cookie.
Cfscrape however handles the type of challenges that look like this:
https://github.com/Sraq-Zit/cloudflare-scrape/blob/954670774887e028cf53f197b95db0d7076c6518/cfscrape/__init__.py#L251-L256

and with websites having this challenge you find the js code such as:
![image](https://user-images.githubusercontent.com/34834428/87877347-b891c780-c9d5-11ea-8f68-8c9c0054b369.png)

in the other side, the website you provided has no such challenge, instead they inject this obfuscated script which contains  the challenge to solve
![image](https://user-images.githubusercontent.com/34834428/87878635-753b5700-c9dd-11ea-8dcc-54a9b75f4390.png)

and that, apparently, is not supported by cfscrape yet
